# Generated by Django 4.1.1 on 2022-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_iva', models.CharField(max_length=50)),
                ('porcentual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
                ('categoria', models.ManyToManyField(to='virtualWaiter.categoria')),
                ('iva', models.ManyToManyField(to='virtualWaiter.iva')),
            ],
        ),
    ]
