# Generated by Django 4.1.1 on 2022-09-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualWaiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='iva',
        ),
        migrations.AddField(
            model_name='articulos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtualWaiter.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='iva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtualWaiter.iva'),
            preserve_default=False,
        ),
    ]
