# Generated by Django 4.1.1 on 2022-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='juego_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=40)),
                ('descripcion_tarea', models.CharField(max_length=400)),
            ],
        ),
    ]
